//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examenFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CotizacionCobro
    {
        public CotizacionCobro()
        {
            this.CotizacionDetalleCobroes = new HashSet<CotizacionDetalleCobro>();
        }
    
        public int idCotizacionDetalle { get; set; }
        public int idCotizacion { get; set; }
        public int idTipoCarga { get; set; }
        public int cantidad { get; set; }
        public string descripcion { get; set; }
        public decimal tamano { get; set; }
        public decimal alto { get; set; }
        public decimal ancho { get; set; }
        public decimal largo { get; set; }
        public decimal peso { get; set; }
        public int idUnidadPeso { get; set; }
    
        public virtual Cotizacion Cotizacion { get; set; }
        public virtual ICollection<CotizacionDetalleCobro> CotizacionDetalleCobroes { get; set; }
    }
}
