//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examenFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CotizacionDetalleCobro
    {
        public int idCotizacionDetalleCobro { get; set; }
        public int idCotizacionDetalle { get; set; }
        public int idTarifa { get; set; }
        public decimal total { get; set; }
    
        public virtual CotizacionCobro CotizacionCobro { get; set; }
        public virtual Tarifa Tarifa { get; set; }
    }
}
