//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examenFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacion
    {
        public Cotizacion()
        {
            this.CotizacionCobroes = new HashSet<CotizacionCobro>();
        }
    
        public int idCotizacion { get; set; }
        public string cliente { get; set; }
        public string buque { get; set; }
        public string viaje { get; set; }
        public string manifiesto { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual ICollection<CotizacionCobro> CotizacionCobroes { get; set; }
    }
}
