//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examenFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarifa
    {
        public Tarifa()
        {
            this.CotizacionDetalleCobroes = new HashSet<CotizacionDetalleCobro>();
        }
    
        public int idTarifa { get; set; }
        public string referencia { get; set; }
        public string descripcion { get; set; }
        public string concepto { get; set; }
        public int idTipoCarga { get; set; }
        public int idTipoCobro { get; set; }
    
        public virtual ICollection<CotizacionDetalleCobro> CotizacionDetalleCobroes { get; set; }
        public virtual TipoCarga TipoCarga { get; set; }
        public virtual TipoCobro TipoCobro { get; set; }
    }
}
