//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examenFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCarga
    {
        public TipoCarga()
        {
            this.Tarifas = new HashSet<Tarifa>();
        }
    
        public int idTipoCarga { get; set; }
        public string referencia { get; set; }
        public string descripcion { get; set; }
        public string tipo { get; set; }
        public string preferencia { get; set; }
        public string comentario { get; set; }
    
        public virtual ICollection<Tarifa> Tarifas { get; set; }
    }
}
